App_auth/urls.py
from django.urls import path
from App_auth import views

app_name = "App_auth"

urlpatterns = [
    path('login/', views.login_view, name='login-page'),
    path('register/', views.signup_view, name='register-page'),
    path('logout/', views.logout_view, name='logout'),
]

App_main/urls.py
from django.urls import path
from App_main import views

app_name = 'App_main'

urlpatterns = [
    path('', views.customer_dashboard, name='customer_dashboard'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_showcase, name='cart-view'),
    path('update-cart/', views.cart_update, name='update-cart'),
    path('checkout/', views.checkout, name='checkout-page'),
    path('purchase/', views.purchase_action, name='purchase'),
    path('profile-view/', views.profile_view, name='profile-view'),
    # path('setiings/', views.profile_settings, name='settings'),
    path('previous-order/', views.previous_orders, name='previous-order'),
    #     Admin
    path('register-with-admin/', views.register_user_by_admin, name='register-with-admin'),
    path('update-product/', views.update_product, name='update-product'),
    path('delete-product/<int:product_key>/', views.delete_product, name='delete-product'),
    path('add-new-product/', views.add_new_product, name='add-new-product'),
    path('add-new-category/', views.add_category, name='add-new-category'),
    path('delete-shortage-record/<int:table_key>/', views.delete_shortage_table, name='delete-shortage-record'),
    path('update-order-status/', views.update_order_status, name='update-order-status'),
    path('update-order-item-quantity/', views.admin_updates_asking_quantity, name='update-order-item-quantity'),
    path('invoice-generator/<int:OrderID>/', views.admin_generates_invoice, name='invoice-generator'),
    #     Admin
    path('boss-admin/', views.boss_admin_dashboard, name='boss_admin_dashboard'),
    path('boss-register-with-admin/', views.register_user_by_boss_admin, name='boss-register-with-admin'),
    path('boss-update-product/', views.boss_update_product, name='boss-update-product'),
    path('boss-delete-product/<int:product_key>/', views.boss_delete_product, name='boss-delete-product'),
    path('boss-add-new-product/', views.boss_add_new_product, name='boss-add-new-product'),
    path('boss-add-new-category/', views.boss_add_category, name='boss-add-new-category'),
    path('boss-delete-shortage-record/<int:table_key>/', views.boss_delete_shortage_table,
         name='boss-delete-shortage-record'),
    path('boss-update-order-status/', views.boss_update_order_status, name='boss-update-order-status'),
    path('boss-update-order-item-quantity/', views.boss_admin_updates_asking_quantity,
         name='boss-update-order-item-quantity'),
    path('boss-invoice-generator/<int:OrderID>/', views.boss_admin_generates_invoice, name='boss-invoice-generator'),
    # OSD
    path('ISD-admin/', views.ISD_admin_dashboard, name='ISD_admin_dashboard'),
    path('register-with-Isd-admin/', views.ISD_admin_register_customer, name='register-with-osd-admin'),
    path('Isd-update-product/', views.ISD_update_product, name='ISD-update-product'),
    path('Isd-delete-product/<int:product_key>/', views.ISD_delete_product, name='ISD-delete-product'),
    path('Isd-add-new-product/', views.ISD_add_new_product, name='ISD-add-new-product'),
    path('Isd-add-new-category/', views.ISD_add_category, name='ISD-add-new-category'),
    path('Isd-delete-shortage-record/<int:table_key>/', views.ISD_delete_shortage_table,
         name='ISD-delete-shortage-record'),
    path('Isd-update-order-status/', views.ISD_update_order_status, name='ISD-update-order-status'),
    path('Isd-update-order-item-quantity/', views.ISD_admin_updates_asking_quantity,
         name='ISD-update-order-item-quantity'),
    path('Isd-invoice-generator/<int:OrderID>/', views.ISD_admin_generates_invoice, name='ISD-invoice-generator'),
    # ISD
    path('OSD-admin/', views.OSD_admin_dashboard, name='OSD_admin_dashboard'),
    path('register-with-osd-admin/', views.OSD_admin_register_customer, name='register-with-osd-admin'),
    path('osd-update-product/', views.OSD_update_product, name='osd-update-product'),
    path('osd-delete-product/<int:product_key>/', views.OSD_delete_product, name='osd-delete-product'),
    path('osd-add-new-product/', views.OSD_add_new_product, name='osd-add-new-product'),
    path('osd-add-new-category/', views.OSD_add_category, name='osd-add-new-category'),
    path('osd-delete-shortage-record/<int:table_key>/', views.OSD_delete_shortage_table,
         name='osd-delete-shortage-record'),
    path('osd-update-order-status/', views.OSD_update_order_status, name='osd-update-order-status'),
    path('osd-update-order-item-quantity/', views.OSD_admin_updates_asking_quantity,
         name='osd-update-order-item-quantity'),
    path('osd-invoice-generator/<int:OrderID>/', views.OSD_admin_generates_invoice, name='osd-invoice-generator'),
    path('this_month_orders/', views.this_month_orders, name='this-month-order'),
]

Pathao/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('accounts/', include('App_auth.urls')),
    path('', include('App_main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/models.py
from django.db import models

# Create your models here.
from App_auth.models import User


class CategoryModel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"


class ProductModel(models.Model):
    product_name = models.CharField(max_length=200)
    category_name = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, related_name='product_category')
    No_of_available = models.IntegerField()
    price_per_unit = models.IntegerField()
    product_details = models.TextField()
    image = models.ImageField(upload_to='product_image/')

    def __str__(self):
        return f"{self.product_name}"


class ShortageOfProduct(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name='shortage_product')
    storageAmount = models.IntegerField()


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_user')
    item = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name='item')
    quantity = models.IntegerField(default=0)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} x {self.item.product_name}'

    def get_total(self):
        total = float(self.item.price_per_unit * self.quantity)
        return format(total, '0.2f')


status_choice = (
    ('Processing', 'Processing'),
    ('Confirmed', 'Confirmed'),
    ('Rejected', 'Rejected'),
    ('Completed', 'Completed'),
    ('Completed', 'Completed'),
    ('Final approval from boss', 'Final approval from boss'),
)


class Order(models.Model):
    order_items = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order')
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    payment_id = models.CharField(max_length=264, blank=True, null=True)
    order_id = models.CharField(max_length=264, blank=True, null=True)
    status = models.CharField(max_length=50, default="Processing", choices=status_choice)
    total_price = models.PositiveIntegerField(blank=True, null=True)

    def get_order_total(self):
        total = 0
        for i in self.order_items.all():
            total += i.quantity * i.item.price_per_unit
        return format(total, '0.2f')


class BillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='billing_profile')
    phone_number = models.CharField(max_length=50, blank=True)
    shop_address = models.CharField(max_length=200, blank=True)
    zip_code = models.CharField(max_length=20, blank=True)
    city_zone = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=70)

    def __str__(self):
        return f"{self.user} billing address"

    def is_full_filled(self):
        fields_name = [f.name for f in self._meta.get_fields()]

        for field in fields_name:
            value = getattr(self, field)
            if value is None or value == "":
                return False
        return True

    class Meta:
        verbose_name_plural = 'BillingAddresses'

App_main/forms.py
from django import forms

from App_auth.models import Profile
from App_main.models import *


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = "__all__"


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', ]


class ProfilePictureChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"


class BillingForm(forms.ModelForm):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'User country code like (+880)'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'class': "selectpicker countrypicker"}))

    class Meta:
        model = BillingAddress
        fields = ['phone_number', 'shop_address', 'zip_code', 'city_zone', 'country']

templates/App_main/BossAdmin_base.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        .main-menu.menu-fixed {
            position: fixed;
            top: 0;
            width: 100%;
            height: auto;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            -webkit-box-shadow: 0 1px 4px rgb(0 0 0 / 6%);
            box-shadow: 0 1px 4px rgb(0 0 0 / 6%);
            z-index: 999;
        }

        .navbar {
            padding: 0;
            min-height: 70px;
            border: 1px solid #EDF1F4;
        }

        .bg-light {
            background-color: #ffffff !important;
        }

        .navbar-nav li a {
            color: #152934 !important;
            font: 17px Roboto, sans-serif !important;
            padding: 20px 25px 20px 20px !important;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu {
            margin-top: 0;
        }

        main {
            margin-top: 100px;
            background-color: rgba(248, 246, 246, 0.55);
        }
    </style>
    <title>Boss Admin Dashboard</title>
</head>
<body>
<header class="main-menu menu-fixed">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'App_main:boss_admin_dashboard' %}">
                <img src="{% static 'images/Pathao_Logo-.svg' %}" alt="Pathao Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link btn btn-success" style="color: #FFFFFF !important;"
                           href="{% url 'App_main:this-month-order' %}">
                            See previous records of Order
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#AdminFormModal">
                            Add Admin
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#CustomerFormModal">
                            Register Customer
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'App_auth:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    {% block main %}
    {% endblock %}
</main>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>

templates/App_main/ISD_Admin_base.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        .main-menu.menu-fixed {
            position: fixed;
            top: 0;
            width: 100%;
            height: auto;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            -webkit-box-shadow: 0 1px 4px rgb(0 0 0 / 6%);
            box-shadow: 0 1px 4px rgb(0 0 0 / 6%);
            z-index: 999;
        }

        .navbar {
            padding: 0;
            min-height: 70px;
            border: 1px solid #EDF1F4;
        }

        .bg-light {
            background-color: #ffffff !important;
        }

        .navbar-nav li a {
            color: #152934 !important;
            font: 17px Roboto, sans-serif !important;
            padding: 20px 25px 20px 20px !important;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu {
            margin-top: 0;
        }

        main {
            margin-top: 100px;
            background-color: rgba(248, 246, 246, 0.55);
        }
    </style>
    <title>ISD Admin Dashboard</title>
</head>
<body>
<header class="main-menu menu-fixed">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'App_main:ISD_admin_dashboard' %}">
                <img src="{% static 'images/Pathao_Logo-.svg' %}" alt="Pathao Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link btn btn-success" style="color: #FFFFFF !important;"
                           href="{% url 'App_main:this-month-order' %}">
                            See previous records of Order
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Register Customer
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'App_auth:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    {% block main %}
    {% endblock %}
</main>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>

templates/App_main/add_new_product.html
{% extends 'App_main/Admin_base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block main %}
    <style>
        .main-content {
            width: 50%;
            border-radius: 20px;
            box-shadow: 0 5px 5px rgba(0, 0, 0, .4);
            margin: 5em auto;
            display: flex;
        }

        .company__info {
            background-color: #008080;
            border-top-left-radius: 20px;
            border-bottom-left-radius: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            color: #fff;
        }

        @media screen and (max-width: 640px) {
            .main-content {
                width: 90%;
            }

            .company__info {
                display: none;
            }
        }

        @media screen and (min-width: 642px) and (max-width: 800px) {
            .main-content {
                width: 70%;
            }
        }

        .row > h2 {
            color: #008080;
        }

        .login_form {
            background-color: #fff;
            border-top-right-radius: 20px;
            border-bottom-right-radius: 20px;
            border-top: 1px solid #ccc;
            border-right: 1px solid #ccc;
        }

        form {
            padding: 0 2em;
        }

        input, select, textarea {
            width: 100%;
            border: 0px solid transparent;
            border-radius: 0;
            border-bottom: 1px solid #aaa;
            padding: 1em .5em .5em;
            padding-left: 2em;
            outline: none;
            margin: 1.5em auto;
            transition: all .5s ease;
        }

        input:focus, select:focus, textarea:focus {
            border-bottom-color: #008080;
            box-shadow: 0 0 5px rgba(0, 80, 80, .4);
            border-radius: 4px;
        }

        .btn {
            transition: all .5s ease;
            width: 70%;
            border-radius: 30px;
            color: #008080;
            font-weight: 600;
            background-color: #fff;
            border: 1px solid #008080;
            margin-top: 1.5em;
            margin-bottom: 1em;
        }

        .btn:hover, .btn:focus {
            background-color: #008080;
            color: #fff;
        }

        #id_category_name {
            width: 80%;
        }
    </style>
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row main-content bg-success pt-2">
            <h4 class="company_title text-center">
                <img src="{% static 'images/Pathao_Logo-.svg' %}" alt="Pathao Logo">
            </h4>
            <div class="col-md-12 col-xs-12 col-sm-12 login_form">
                <div class="container-fluid">
                    <div class="row">
                        <h2 class="m-3">ADD NEW PRODUCT</h2>
                    </div>
                    <div class="row">
                        <form method="post" class="form-group" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset>
                                <label for="id_product_name">Product Name</label>
                                {{ form.product_name }}
                                <label for="id_category_name">Category Name</label> <br>
                                {{ form.category_name }}
                                <a href="#id-add-category" data-bs-toggle="modal" data-bs-target="#id-add-category"
                                   onclick="document.getElementById('id-add-category').style.display='block';">Add
                                    Category</a>
                                <label for="id_No_of_available">No of Availability</label>
                                {{ form.No_of_available }}
                                <label for="id_price_per_unit">Price per unit</label>
                                {{ form.price_per_unit }}
                                <label for="id_product_details">Product Details</label>
                                {{ form.product_details }}
                                <label for="id_image">Product Image</label>
                                {{ form.image }}
                            </fieldset>
                            <div class="row">
                                <input type="submit" value="Submit" class="btn">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="id-add-category" style="display: none;" tabindex="-1"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add new category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'App_main:add-new-category' %}" method="post" class="justify-content-center">
                        {% csrf_token %}
                        <input type="text" name="cat-name"
                               style="width: 100%; background-color: rgb(208,208,208); color: #000000;">
                        <button class="btn btn-success w-100" type="submit">
                            Add
                        </button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary w-25 float-right" data-bs-dismiss="modal">Close
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
{% endblock %}

templates/App_main/boss_add_new_product.html
{% extends 'App_main/Admin_base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block main %}
    <style>
        .main-content {
            width: 50%;
            border-radius: 20px;
            box-shadow: 0 5px 5px rgba(0, 0, 0, .4);
            margin: 5em auto;
            display: flex;
        }

        .company__info {
            background-color: #008080;
            border-top-left-radius: 20px;
            border-bottom-left-radius: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            color: #fff;
        }

        @media screen and (max-width: 640px) {
            .main-content {
                width: 90%;
            }

            .company__info {
                display: none;
            }
        }

        @media screen and (min-width: 642px) and (max-width: 800px) {
            .main-content {
                width: 70%;
            }
        }

        .row > h2 {
            color: #008080;
        }

        .login_form {
            background-color: #fff;
            border-top-right-radius: 20px;
            border-bottom-right-radius: 20px;
            border-top: 1px solid #ccc;
            border-right: 1px solid #ccc;
        }

        form {
            padding: 0 2em;
        }

        input, select, textarea {
            width: 100%;
            border: 0px solid transparent;
            border-radius: 0;
            border-bottom: 1px solid #aaa;
            padding: 1em .5em .5em;
            padding-left: 2em;
            outline: none;
            margin: 1.5em auto;
            transition: all .5s ease;
        }

        input:focus, select:focus, textarea:focus {
            border-bottom-color: #008080;
            box-shadow: 0 0 5px rgba(0, 80, 80, .4);
            border-radius: 4px;
        }

        .btn {
            transition: all .5s ease;
            width: 70%;
            border-radius: 30px;
            color: #008080;
            font-weight: 600;
            background-color: #fff;
            border: 1px solid #008080;
            margin-top: 1.5em;
            margin-bottom: 1em;
        }

        .btn:hover, .btn:focus {
            background-color: #008080;
            color: #fff;
        }

        #id_category_name {
            width: 80%;
        }
    </style>
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row main-content bg-success pt-2">
            <h4 class="company_title text-center">
                <img src="{% static 'images/Pathao_Logo-.svg' %}" alt="Pathao Logo">
            </h4>
            <div class="col-md-12 col-xs-12 col-sm-12 login_form">
                <div class="container-fluid">
                    <div class="row">
                        <h2 class="m-3">ADD NEW PRODUCT</h2>
                    </div>
                    <div class="row">
                        <form method="post" class="form-group" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset>
                                <label for="id_product_name">Product Name</label>
                                {{ form.product_name }}
                                <label for="id_category_name">Category Name</label> <br>
                                {{ form.category_name }}
                                <a href="#id-add-category" data-bs-toggle="modal" data-bs-target="#id-add-category"
                                   onclick="document.getElementById('id-add-category').style.display='block';">Add
                                    Category</a>
                                <label for="id_No_of_available">No of Availability</label>
                                {{ form.No_of_available }}
                                <label for="id_price_per_unit">Price per unit</label>
                                {{ form.price_per_unit }}
                                <label for="id_product_details">Product Details</label>
                                {{ form.product_details }}
                                <label for="id_image">Product Image</label>
                                {{ form.image }}
                            </fieldset>
                            <div class="row">
                                <input type="submit" value="Submit" class="btn">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="id-add-category" style="display: none;" tabindex="-1"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add new category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'App_main:boss-add-new-category' %}" method="post" class="justify-content-center">
                        {% csrf_token %}
                        <input type="text" name="cat-name"
                               style="width: 100%; background-color: rgb(208,208,208); color: #000000;">
                        <button class="btn btn-success w-100" type="submit">
                            Add
                        </button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary w-25 float-right" data-bs-dismiss="modal">Close
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
{% endblock %}

templates/App_main/customer_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>